### ISSUE TITLE
problem reading JSON

### ISSUE THREAD

**Issue by edgarmedina1801** [zengarden/light_head_rcnn#37]
Hello,

I am training a network with a modified base model from scratch. but I'm having this error two times before having a complete error and crash the ipython (terminal). Why am I obtaining this error?, it looks like a dataset problem or during the reading process.

Process _Worker-8:
Traceback (most recent call last):
  File "/home/edgar/light_head_rcnn/experiments/lizeming/light_head_rcnn.ori_res101.coco.ps_roialign/dataset.py", line 96, in get_data_for_singlegpu
    record = json.loads(raw_line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 219 (char 218)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/edgar/light_head_rcnn/lib/utils/dpflow/data_provider.py", line 207, in run
    dp = self.map_func(dp_list)
  File "/home/edgar/light_head_rcnn/experiments/lizeming/light_head_rcnn.ori_res101.coco.ps_roialign/dataset.py", line 105, in get_data_for_singlegpu
    record = json.loads(raw_line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 219 (char 218)

##########################

Process _Worker-1:
Traceback (most recent call last):
  File "/home/edgar/light_head_rcnn/experiments/lizeming/light_head_rcnn.ori_res101.coco.ps_roialign/dataset.py", line 96, in get_data_for_singlegpu
    record = json.loads(raw_line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 219 (char 218)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/edgar/light_head_rcnn/lib/utils/dpflow/data_provider.py", line 207, in run
    dp = self.map_func(dp_list)
  File "/home/edgar/light_head_rcnn/experiments/lizeming/light_head_rcnn.ori_res101.coco.ps_roialign/dataset.py", line 105, in get_data_for_singlegpu
    record = json.loads(raw_line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 219 (char 218)

**Comment by edgarmedina1801** [comment]
Problem solved. Files must be downloaded by yourself, this error is generated by corrupted or uncompleted files.
