### ISSUE TITLE
not able to run test.py

### ISSUE THREAD

**Issue by aggpankaj2** [zengarden/light_head_rcnn#46]
while running 
root@982633c0cbbf:/dh/home/administrator/users_local/mamta/LightHead/lighthead_ROOT/light_head_rcnn/experiments/lizeming/light_head_rcnn.ori_res101.coco# **python3 test.py -d 0 -se 1**

getting error 
2018-08-27 09:37:02.247790: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:170 : Not found: Unsuccessful TensorSliceReader constructor: **Failed to find any matching files for /dh/home/administrator/users_local/LightHead/lighthead_ROOT/light_head_rcnn/output/root/light_head_rcnn.ori_res101.coco/eval_dump/epoch_1.ckpt**

Not able to understand from where i can get epoch_1.ckpt

**Comment by Mikcal** [comment]
Hello, have you solved it? I had the same problem.

Thank you!

**Comment by aggpankaj2** [comment]
@Mikcal yes, problem solved now. It need to train first before running test.py.
Did you got MAP

**Comment by Mikcal** [comment]
NO，the training has not been successful and there are other problems.

**Comment by Mikcal** [comment]
I had some problems while training. I downloaded the officially prepared odformat archive, but I don't have a json file, can I train it? 
If it is convenient, can you share the files in your data directory with me?
Thank you！

**Comment by aggpankaj2** [comment]
One more thing you can directly run test.py also . some needed file like (epoch_26.ckpt) is on googledrive. you can download and directly run test.py

**Comment by Mikcal** [comment]
How can you see how long it takes to detect one picture.

**Comment by aggpankaj2** [comment]
it took 32 mnt for 5000 images to test ....... . did you run test.py ??????? if yes what MAP you got

**Comment by sflvsm** [comment]
plz tell me what‘s .odgt file?

**Comment by aggpankaj2** [comment]
@sflvsm  on coco

**Comment by TonyTangYu** [comment]
@aggpankaj2  I downloaded the file on googledrive but I didn't find epoch_26.ckpt. I got three files, namely  epoch_26.ckpt.data-00000-of-00001, epoch_26.ckpt.index, epoch_26.ckpt.meta. Should I rename one of these three files? But which one? I have tried respectively but different errors occurred. How can I fix it?

**Comment by karansomaiah** [comment]
@TonyTangYu No you don't have to rename any of these specific ones.
All you have to do to run the test script is,
``` 
python3 test.py -d 0-7 -se 26
```
Here, *0-7* is the 8 GPUs the author has, so if you have two you can mention it as *0-1* or *0,1*. The *-se* argument gives the saved checkpoint. You need all the three files, no need to rename. Since the checkpoint number is 26, just assign 26 to the *-se* argument.

**Comment by nithishc829** [comment]
I have some issues with test.py file  I am getting this error
```
 file name ==>  /home/nithish/python/RFCN/light_head_rcnn/lib/lib_kernel/lib_psroi_pooling/psroi_pooling.so
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    import network_desp
  File "/home/nithish/python/RFCN/light_head_rcnn/experiments/lizeming/rfcn_reproduce.ori_res101.coco.baseline/network_desp.py", line 30, in <module>
    from lib_kernel.lib_psroi_pooling import psroi_pooling_op, psroi_pooling_op_grad
  File "/home/nithish/python/RFCN/light_head_rcnn/lib/lib_kernel/lib_psroi_pooling/psroi_pooling_op.py", line 6, in <module>
    _psroi_pooling_module = tf.load_op_library(filename)
  File "/home/nithish/python/RFCN/light_head_rcnn/experiments/lizeming/rfcn_reproduce.ori_res101.coco.baseline/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

```

I am running this like `python test.py -d "0" -se 28`

Previously I was able to run this  I installed ipykernel and since then I have trouble running this.
