### ISSUE TITLE
There are a lot of errors in testing. Using 1080ti,tensorflow1.5.0,python3.6

### ISSUE THREAD

**Issue by mypicara** [zengarden/light_head_rcnn#47]
Traceback (most recent call last):
  File "test.py", line 241, in <module>
    eval_all(args)
  File "test.py", line 131, in eval_all
    func, inputs = load_model(model_file, devs[0])
  File "test.py", line 35, in load_model
    sess = tf.Session(config=tfconfig)
  File "/home/lucifer/anaconda3/envs/slam/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1509, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/lucifer/anaconda3/envs/slam/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 628, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/lucifer/anaconda3/envs/slam/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

**Comment by mypicara** [comment]
And there is another error in CUDA "Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error"

**Comment by Mikcal** [comment]
Have you solved it? I had the same problem.

Thank you!
