### ISSUE TITLE
No op named PSAlignPool in defined operations

### ISSUE THREAD

**Issue by YoungDav** [zengarden/light_head_rcnn#74]
hi：
i trans model.ckpt to .pb according to [https://github.com/zengarden/light_head_rcnn/issues/66](url)
but when i start inference function , it raise such error:

> Traceback (most recent call last):
  File "pb_inference.py", line 36, in <module>
    model_fn = DetectionModel()
  File "pb_inference.py", line 16, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "/home/luban/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/home/luban/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 541, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named PSAlignPool in defined operations.

**Comment by YoungDav** [comment]
i think may solve it:
add this line before tf.import_graph_def(od_graph_def, name='')
> PSAlignPool = tf.load_op_library('lib/lib_kernel/lib_psalign_pooling/psalign_pooling.so')

**Comment by Willis90** [comment]
@YoungDav hi I want to freeze CKPT into pb,But I do not know what's name of output node?What's the output node name do you use ?I use res_v1_101 for my backbone net.Can you give some help?Thank you。
